all:  generating clean

# say_hello:
	# echo "hello oombu"
	# @echo "hello world"

generating:
	@echo "Generating Text Files  .... "
	@touch Making-{1..10}.txt
	@ls

clean:
	@echo "Cleaning your files "
	@rm *.txt
