import numpy as np
a = np.array([1,2,3])
print(type(a))
x = np.zeros((3,4))
print(x)
z = np.ones((2,2))
print(z)
j = np.full((2,2),"jk")
print(j)
b = np.arange(10,30,5)
print(b)
c = np.linspace(0,10/8,10)
print(c)
d = np.random.rand(5,6)
print(d)
e = np.empty((2,3))
print(e)
print(e.ndim)
print(e.shape)
print(e.size)
print(e.dtype)
print(e.itemsize)
print(e.reshape((2,3)))
print(e[0::3])
